messages:
  error:
    # The colours of the text, in hex codes. Include the # (i.e. #FFFFFF)
    color:
      bracket: "#c2bfb8"
      message: "#ff6f6f"
  prefix:
    text: "NerdMinigames"
    color: "#e89e15"